export interface Module {
  id: number;
  title: string;
  shortTitle: string;
  part: number;
  partTitle: string;
  description: string;
  estimatedTime: number;
  objectives: string[];
  sections: ModuleSection[];
}

export interface ModuleSection {
  id: string;
  title: string;
  type: 'content' | 'interactive' | 'quiz' | 'resources';
}

export interface ModuleProgress {
  moduleId: number;
  sectionsCompleted: string[];
  quizCompleted: boolean;
  quizScore: number | null;
  timeSpent: number;
  lastAccessed: string;
}

export const MODULES: Module[] = [
  {
    id: 1,
    title: 'Introduction to Accounting',
    shortTitle: 'Introduction',
    part: 1,
    partTitle: 'Foundations of Accounting',
    description: 'Discover what accounting is, why it matters, and how you already use it in daily life.',
    estimatedTime: 30,
    objectives: [
      'Define accounting and explain its purpose in personal and business contexts',
      'Distinguish between financial accounting, managerial accounting, and tax accounting',
      'Recognize how accounting information is used in daily decision-making',
      'Understand the role of accounting standards and why they matter',
    ],
    sections: [
      { id: '1.1', title: 'What is Accounting?', type: 'content' },
      { id: '1.2', title: 'The Accounting Cycle Overview', type: 'content' },
      { id: '1.3', title: 'Personal Finance Awareness Assessment', type: 'interactive' },
      { id: '1.4', title: 'The Coffee Shop Decision', type: 'content' },
      { id: '1.5', title: 'Knowledge Check', type: 'quiz' },
      { id: '1.6', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 2,
    title: 'The Accounting Equation',
    shortTitle: 'Accounting Equation',
    part: 1,
    partTitle: 'Foundations of Accounting',
    description: 'Master the fundamental equation that underlies all accounting: Assets = Liabilities + Equity.',
    estimatedTime: 45,
    objectives: [
      'State and explain the fundamental accounting equation',
      'Define assets, liabilities, and equity with examples',
      'Calculate personal net worth using the accounting equation',
      'Understand how every transaction maintains the equation balance',
      'Apply the equation to analyze simple business scenarios',
    ],
    sections: [
      { id: '2.1', title: 'The Foundation of All Accounting', type: 'content' },
      { id: '2.2', title: 'The Equation Always Balances', type: 'content' },
      { id: '2.3', title: 'Net Worth Calculator', type: 'interactive' },
      { id: '2.4', title: 'Transaction Impact Visualizer', type: 'interactive' },
      { id: '2.5', title: 'First-Time Home Buyer Scenario', type: 'content' },
      { id: '2.6', title: 'Knowledge Check', type: 'quiz' },
      { id: '2.7', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 3,
    title: 'Double-Entry Bookkeeping & The General Ledger',
    shortTitle: 'Double-Entry',
    part: 1,
    partTitle: 'Foundations of Accounting',
    description: 'Learn the universal standard of double-entry bookkeeping and how to record transactions.',
    estimatedTime: 60,
    objectives: [
      'Explain why double-entry bookkeeping is the universal standard',
      'Define debits and credits correctly for each account type',
      'Record transactions using proper journal entry format',
      'Understand the structure and purpose of a general ledger',
      'Post journal entries to T-accounts',
      'Identify and correct common recording errors',
    ],
    sections: [
      { id: '3.1', title: 'The Genius of Double-Entry', type: 'content' },
      { id: '3.2', title: 'The Chart of Accounts', type: 'content' },
      { id: '3.3', title: 'Journal Entries', type: 'content' },
      { id: '3.4', title: 'The General Ledger', type: 'content' },
      { id: '3.5', title: 'Bookkeeping Simulator', type: 'interactive' },
      { id: '3.6', title: 'Transaction Decoder', type: 'interactive' },
      { id: '3.7', title: 'Knowledge Check', type: 'quiz' },
      { id: '3.8', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 4,
    title: 'The Income Statement (Profit & Loss)',
    shortTitle: 'Income Statement',
    part: 2,
    partTitle: 'Financial Statements',
    description: 'Understand how income statements reveal profitability over time.',
    estimatedTime: 45,
    objectives: [
      'Explain the purpose and structure of an income statement',
      'Distinguish between different types of revenue and expenses',
      'Calculate gross profit, operating income, and net income',
      'Analyze income statement ratios (profit margins)',
      'Create a personal or small business income statement',
      'Interpret income statements to make financial decisions',
    ],
    sections: [
      { id: '4.1', title: 'Understanding the Income Statement', type: 'content' },
      { id: '4.2', title: 'Personal Income Statement', type: 'content' },
      { id: '4.3', title: 'Analyzing Profitability', type: 'content' },
      { id: '4.4', title: 'Income Statement Builder', type: 'interactive' },
      { id: '4.5', title: 'Profit Margin Analyzer', type: 'interactive' },
      { id: '4.6', title: 'The Struggling Restaurant', type: 'content' },
      { id: '4.7', title: 'Knowledge Check', type: 'quiz' },
      { id: '4.8', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 5,
    title: 'The Balance Sheet',
    shortTitle: 'Balance Sheet',
    part: 2,
    partTitle: 'Financial Statements',
    description: 'Learn to read and create balance sheets that show financial position at a point in time.',
    estimatedTime: 45,
    objectives: [
      'Explain the purpose and structure of a balance sheet',
      'Classify items as current vs. non-current assets/liabilities',
      'Understand shareholders equity components',
      'Analyze balance sheet ratios (liquidity, solvency)',
      'Read and interpret real balance sheets',
      'Create a personal balance sheet',
    ],
    sections: [
      { id: '5.1', title: 'The Financial Snapshot', type: 'content' },
      { id: '5.2', title: 'Key Balance Sheet Ratios', type: 'content' },
      { id: '5.3', title: 'Balance Sheet Builder', type: 'interactive' },
      { id: '5.4', title: 'Financial Health Dashboard', type: 'interactive' },
      { id: '5.5', title: 'Knowledge Check', type: 'quiz' },
      { id: '5.6', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 6,
    title: 'The Cash Flow Statement',
    shortTitle: 'Cash Flow',
    part: 2,
    partTitle: 'Financial Statements',
    description: 'Discover why cash is king and how to track where money actually goes.',
    estimatedTime: 45,
    objectives: [
      'Explain why profitable businesses can run out of cash',
      'Distinguish between the three sections of cash flow statements',
      'Calculate cash flows from operations using indirect method',
      'Analyze cash flow patterns to assess business health',
      'Apply cash flow concepts to personal finance',
    ],
    sections: [
      { id: '6.1', title: 'Cash is King', type: 'content' },
      { id: '6.2', title: 'Three Sections of Cash Flow', type: 'content' },
      { id: '6.3', title: 'Cash Flow Forecaster', type: 'interactive' },
      { id: '6.4', title: 'The Cash Crunch', type: 'content' },
      { id: '6.5', title: 'Knowledge Check', type: 'quiz' },
      { id: '6.6', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 7,
    title: 'Budgeting Mastery',
    shortTitle: 'Budgeting',
    part: 3,
    partTitle: 'Practical Accounting Skills',
    description: 'Master budgeting methodologies and variance analysis to take control of your finances.',
    estimatedTime: 50,
    objectives: [
      'Create effective budgets using multiple methodologies',
      'Implement variance analysis to track performance',
      'Adjust budgets based on actual results',
      'Apply zero-based budgeting principles',
      'Use budgets as decision-making tools',
    ],
    sections: [
      { id: '7.1', title: 'What is Budgeting?', type: 'content' },
      { id: '7.2', title: 'Budgeting Methodologies', type: 'content' },
      { id: '7.3', title: 'Creating Your Budget', type: 'content' },
      { id: '7.4', title: 'Budget Builder', type: 'interactive' },
      { id: '7.5', title: 'Variance Analysis', type: 'content' },
      { id: '7.6', title: 'The Emergency Fund Journey', type: 'content' },
      { id: '7.7', title: 'Knowledge Check', type: 'quiz' },
      { id: '7.8', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 8,
    title: 'Recording & Organizing',
    shortTitle: 'Record-Keeping',
    part: 3,
    partTitle: 'Practical Accounting Skills',
    description: 'Master document management, filing systems, and bank reconciliation.',
    estimatedTime: 40,
    objectives: [
      'Understand the importance of organized financial records',
      'Identify and categorize source documents',
      'Implement effective filing systems for personal and business use',
      'Perform bank reconciliation',
      'Apply document retention guidelines',
      'Build sustainable record-keeping habits',
    ],
    sections: [
      { id: '8.1', title: 'Why Organization Matters', type: 'content' },
      { id: '8.2', title: 'Source Documents', type: 'content' },
      { id: '8.3', title: 'Filing Systems', type: 'content' },
      { id: '8.4', title: 'Document Retention', type: 'content' },
      { id: '8.5', title: 'Bank Reconciliation', type: 'content' },
      { id: '8.6', title: 'Digital vs. Physical Records', type: 'content' },
      { id: '8.7', title: 'Building Good Habits', type: 'content' },
      { id: '8.8', title: 'Knowledge Check', type: 'quiz' },
      { id: '8.9', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 9,
    title: 'Loans & Interest',
    shortTitle: 'Loans & Interest',
    part: 3,
    partTitle: 'Practical Accounting Skills',
    description: 'Understand how interest works, compare loans, and master the math of borrowing and saving.',
    estimatedTime: 45,
    objectives: [
      'Understand the difference between simple and compound interest',
      'Calculate interest using different compounding frequencies',
      'Apply the Rule of 72 for quick estimations',
      'Understand amortization and loan structures',
      'Compare loans effectively to find the best deal',
      'Recognize the power of extra principal payments',
    ],
    sections: [
      { id: '9.1', title: 'Understanding Interest', type: 'content' },
      { id: '9.2', title: 'Simple vs. Compound Interest', type: 'content' },
      { id: '9.3', title: 'Compounding Frequency', type: 'content' },
      { id: '9.4', title: 'The Rule of 72', type: 'content' },
      { id: '9.5', title: 'Loan Types and Structures', type: 'content' },
      { id: '9.6', title: 'Amortization Explained', type: 'content' },
      { id: '9.7', title: 'Comparing Loans', type: 'content' },
      { id: '9.8', title: 'Knowledge Check', type: 'quiz' },
      { id: '9.9', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 10,
    title: 'Cash vs. Accrual Accounting',
    shortTitle: 'Cash vs. Accrual',
    part: 3,
    partTitle: 'Practical Accounting Skills',
    description: 'Compare cash and accrual accounting methods to choose the right approach for your needs.',
    estimatedTime: 40,
    objectives: [
      'Explain the difference between cash and accrual accounting',
      'Apply the matching principle in accrual accounting',
      'Identify when each method is appropriate',
      'Understand accounts receivable, payable, and accrued expenses',
      'Recognize the impact of method choice on financial statements',
      'Prepare basic adjusting entries',
    ],
    sections: [
      { id: '10.1', title: 'Two Ways to Track Money', type: 'content' },
      { id: '10.2', title: 'Cash Basis Accounting', type: 'content' },
      { id: '10.3', title: 'Accrual Basis Accounting', type: 'content' },
      { id: '10.4', title: 'Side-by-Side Comparison', type: 'content' },
      { id: '10.5', title: 'Which Method Should You Use?', type: 'content' },
      { id: '10.6', title: 'Modified Cash Basis', type: 'content' },
      { id: '10.7', title: 'Adjusting Entries', type: 'content' },
      { id: '10.8', title: 'Knowledge Check', type: 'quiz' },
      { id: '10.9', title: 'Resources', type: 'resources' },
    ],
  },
  {
    id: 11,
    title: 'Financial Analysis',
    shortTitle: 'Financial Analysis',
    part: 4,
    partTitle: 'Applied Accounting',
    description: 'Master financial ratio analysis to evaluate performance and make data-driven decisions.',
    estimatedTime: 50,
    objectives: [
      'Perform horizontal and vertical analysis of financial statements',
      'Calculate and interpret liquidity ratios',
      'Calculate and interpret solvency ratios',
      'Calculate and interpret profitability ratios',
      'Calculate and interpret efficiency ratios',
      'Understand the limitations of ratio analysis',
      'Apply ratio analysis to real-world decisions',
    ],
    sections: [
      { id: '11.1', title: 'Introduction to Financial Analysis', type: 'content' },
      { id: '11.2', title: 'Horizontal Analysis', type: 'content' },
      { id: '11.3', title: 'Vertical Analysis', type: 'content' },
      { id: '11.4', title: 'Liquidity Ratios', type: 'content' },
      { id: '11.5', title: 'Solvency Ratios', type: 'content' },
      { id: '11.6', title: 'Profitability Ratios', type: 'content' },
      { id: '11.7', title: 'Efficiency Ratios', type: 'content' },
      { id: '11.8', title: 'Quick Reference: Key Ratios', type: 'content' },
      { id: '11.9', title: 'Limitations of Ratio Analysis', type: 'content' },
      { id: '11.10', title: 'Knowledge Check', type: 'quiz' },
      { id: '11.11', title: 'Module Summary', type: 'content' },
    ],
  },
  {
    id: 12,
    title: 'Compliance & Tax Basics',
    shortTitle: 'Compliance & Tax',
    part: 4,
    partTitle: 'Applied Accounting',
    description: 'Understand accounting standards, tax fundamentals, and internal controls for compliance.',
    estimatedTime: 45,
    objectives: [
      'Understand the purpose of GAAP and IFRS accounting standards',
      'Explain how income taxes work and progressive tax brackets',
      'Distinguish between tax deductions and tax credits',
      'Identify common tax forms and their purposes',
      'Apply legal tax planning strategies',
      'Understand internal controls and their importance',
      'Know key tax deadlines and record retention requirements',
    ],
    sections: [
      { id: '12.1', title: 'Introduction to Compliance', type: 'content' },
      { id: '12.2', title: 'Accounting Standards Overview', type: 'content' },
      { id: '12.3', title: 'Understanding Income Taxes', type: 'content' },
      { id: '12.4', title: 'Deductions vs. Credits', type: 'content' },
      { id: '12.5', title: 'Common Tax Forms', type: 'content' },
      { id: '12.6', title: 'Tax Planning Strategies', type: 'content' },
      { id: '12.7', title: 'Internal Controls', type: 'content' },
      { id: '12.8', title: 'Key Deadlines & Record Retention', type: 'content' },
      { id: '12.9', title: 'Knowledge Check', type: 'quiz' },
      { id: '12.10', title: 'Module Summary', type: 'content' },
    ],
  },
];

export const PARTS = [
  { id: 1, title: 'Foundations of Accounting', modules: [1, 2, 3] },
  { id: 2, title: 'Financial Statements', modules: [4, 5, 6] },
  { id: 3, title: 'Practical Accounting Skills', modules: [7, 8, 9, 10] },
  { id: 4, title: 'Applied Accounting', modules: [11, 12] },
];
