import type { QuizQuestion } from '../../types';

export const module09Quiz: QuizQuestion[] = [
  {
    id: 'm9-q1',
    type: 'multiple-choice',
    question: 'What is the difference between principal and interest?',
    options: [
      'Principal is the fee; interest is the original amount',
      'Principal is the original amount borrowed; interest is the cost of borrowing',
      'They are the same thing',
      'Principal is paid monthly; interest is paid annually',
    ],
    correctAnswer: 1,
    explanation: 'Principal is the original amount borrowed or invested. Interest is the cost of borrowing money (for loans) or the return on investment (for savings).',
    difficulty: 'easy',
  },
  {
    id: 'm9-q2',
    type: 'multiple-choice',
    question: 'What does APR stand for?',
    options: [
      'Annual Payment Rate',
      'Average Principal Return',
      'Annual Percentage Rate',
      'Applied Payment Ratio',
    ],
    correctAnswer: 2,
    explanation: 'APR stands for Annual Percentage Rate. It represents the yearly cost of borrowing, including interest and certain fees, expressed as a percentage.',
    difficulty: 'easy',
  },
  {
    id: 'm9-q3',
    type: 'multiple-choice',
    question: 'With compound interest, what earns interest?',
    options: [
      'Only the original principal',
      'Only the interest earned',
      'Both the principal and accumulated interest',
      'Neither—compound interest is fixed',
    ],
    correctAnswer: 2,
    explanation: 'With compound interest, you earn interest on both your original principal AND the interest that has already been added. This creates exponential growth over time.',
    difficulty: 'easy',
  },
  {
    id: 'm9-q4',
    type: 'multiple-choice',
    question: 'If you borrow $10,000 at 6% simple interest for 3 years, how much interest will you pay?',
    options: [
      '$600',
      '$1,800',
      '$1,910',
      '$3,000',
    ],
    correctAnswer: 1,
    explanation: 'Simple Interest = Principal × Rate × Time = $10,000 × 0.06 × 3 = $1,800. Simple interest is calculated only on the original principal.',
    difficulty: 'medium',
  },
  {
    id: 'm9-q5',
    type: 'multiple-choice',
    question: 'What is an amortized loan?',
    options: [
      'A loan with variable interest rates',
      'A loan paid off in equal periodic payments that include both principal and interest',
      'A loan that never has to be paid back',
      'A loan with interest-only payments',
    ],
    correctAnswer: 1,
    explanation: 'An amortized loan is repaid through regular payments that cover both interest and principal. Early payments are mostly interest; later payments are mostly principal.',
    difficulty: 'medium',
  },
  {
    id: 'm9-q6',
    type: 'multiple-choice',
    question: 'How often does interest compound if a savings account has "daily compounding"?',
    options: [
      'Once per year',
      'Once per month',
      'Once per week',
      'Every day',
    ],
    correctAnswer: 3,
    explanation: 'Daily compounding means interest is calculated and added to your balance every day. More frequent compounding leads to higher effective returns.',
    difficulty: 'easy',
  },
  {
    id: 'm9-q7',
    type: 'multiple-choice',
    question: 'What is the Rule of 72 used for?',
    options: [
      'Calculating monthly payments',
      'Estimating how long it takes for money to double',
      'Determining the best interest rate',
      'Computing total interest paid',
    ],
    correctAnswer: 1,
    explanation: 'The Rule of 72 estimates how long it takes for an investment to double. Divide 72 by the interest rate to get the approximate number of years.',
    difficulty: 'medium',
  },
  {
    id: 'm9-q8',
    type: 'multiple-choice',
    question: 'Using the Rule of 72, approximately how many years does it take to double your money at 8% interest?',
    options: [
      '6 years',
      '8 years',
      '9 years',
      '12 years',
    ],
    correctAnswer: 2,
    explanation: 'Rule of 72: 72 ÷ 8 = 9 years. At 8% annual return, your money will approximately double every 9 years.',
    difficulty: 'easy',
  },
  {
    id: 'm9-q9',
    type: 'multiple-choice',
    question: 'What happens to the interest portion of loan payments over time in an amortized loan?',
    options: [
      'It stays the same',
      'It increases each month',
      'It decreases each month',
      'It changes randomly',
    ],
    correctAnswer: 2,
    explanation: 'In an amortized loan, early payments are mostly interest. As you pay down the principal, the interest portion decreases and the principal portion increases.',
    difficulty: 'medium',
  },
  {
    id: 'm9-q10',
    type: 'multiple-choice',
    question: 'Which type of interest is typically better for savers?',
    options: [
      'Simple interest',
      'Compound interest',
      'They are equally good',
      'It depends on the tax rate',
    ],
    correctAnswer: 1,
    explanation: 'Compound interest is better for savers because you earn interest on your interest. Over time, this "interest on interest" significantly boosts your returns.',
    difficulty: 'easy',
  },
  {
    id: 'm9-q11',
    type: 'multiple-choice',
    question: 'If Loan A has a lower APR but higher fees than Loan B, which metric should you compare for true cost?',
    options: [
      'Just the APR',
      'Just the fees',
      'The APY or total cost of the loan',
      'The monthly payment amount',
    ],
    correctAnswer: 2,
    explanation: 'To compare loans with different fee structures, look at the total cost of the loan or the APY (which includes compounding effects). APR alone may not tell the whole story.',
    difficulty: 'medium',
  },
  {
    id: 'm9-q12',
    type: 'multiple-choice',
    question: 'What is the main benefit of making extra principal payments on a loan?',
    options: [
      'It increases your credit score immediately',
      'It reduces total interest paid and shortens the loan term',
      'It lowers your monthly payment',
      'It increases the APR',
    ],
    correctAnswer: 1,
    explanation: 'Extra principal payments reduce your outstanding balance faster, meaning you pay less interest over time and can pay off the loan earlier.',
    difficulty: 'medium',
  },
];
