import type { QuizQuestion } from '../../types';

export const module02Quiz: QuizQuestion[] = [
  {
    id: 'm2-q1',
    type: 'multiple-choice',
    question: 'What is the fundamental accounting equation?',
    options: [
      'Revenue - Expenses = Profit',
      'Assets = Liabilities + Owner\'s Equity',
      'Cash In - Cash Out = Balance',
      'Income - Taxes = Net Income',
    ],
    correctAnswer: 1,
    explanation: 'The fundamental accounting equation is Assets = Liabilities + Owner\'s Equity. This equation must always balance and is the foundation of all accounting.',
    difficulty: 'easy',
  },
  {
    id: 'm2-q2',
    type: 'multiple-choice',
    question: 'Which of the following is considered a current asset?',
    options: [
      'A house you own',
      'A car loan',
      'Money in your checking account',
      'A 30-year mortgage',
    ],
    correctAnswer: 2,
    explanation: 'Current assets can be converted to cash within one year. A checking account is a current asset because you can access the money immediately.',
    difficulty: 'easy',
  },
  {
    id: 'm2-q3',
    type: 'multiple-choice',
    question: 'If you have $50,000 in assets and $30,000 in liabilities, what is your net worth (equity)?',
    options: [
      '$80,000',
      '$30,000',
      '$20,000',
      '$50,000',
    ],
    correctAnswer: 2,
    explanation: 'Net Worth = Assets - Liabilities. So $50,000 - $30,000 = $20,000. This is your equity—what\'s truly yours after paying all debts.',
    difficulty: 'easy',
  },
  {
    id: 'm2-q4',
    type: 'multiple-choice',
    question: 'You receive a $2,000 paycheck deposited to your bank account. How does this affect the accounting equation?',
    options: [
      'Assets increase by $2,000, Liabilities increase by $2,000',
      'Assets increase by $2,000, Equity increases by $2,000',
      'Assets decrease by $2,000, Equity decreases by $2,000',
      'Liabilities decrease by $2,000, Equity increases by $2,000',
    ],
    correctAnswer: 1,
    explanation: 'When you receive income, your Cash (an asset) increases, and your Equity increases by the same amount (through revenue). The equation stays balanced.',
    difficulty: 'medium',
  },
  {
    id: 'm2-q5',
    type: 'multiple-choice',
    question: 'You buy a $500 laptop using your credit card. How does this affect the equation?',
    options: [
      'Assets +$500, Liabilities +$500',
      'Assets -$500, Equity -$500',
      'Assets +$500, Equity +$500',
      'Liabilities -$500, Equity +$500',
    ],
    correctAnswer: 0,
    explanation: 'When you buy something on credit, you gain an asset (the laptop, worth $500) and also gain a liability (credit card debt of $500). Both sides increase equally.',
    difficulty: 'medium',
  },
  {
    id: 'm2-q6',
    type: 'multiple-choice',
    question: 'Which of the following is a long-term liability?',
    options: [
      'Credit card balance due this month',
      'A 30-year mortgage',
      'Utility bill due next week',
      'Groceries purchased on credit',
    ],
    correctAnswer: 1,
    explanation: 'Long-term liabilities are obligations due beyond one year. A 30-year mortgage is a long-term liability because it will take many years to pay off.',
    difficulty: 'easy',
  },
  {
    id: 'm2-q7',
    type: 'multiple-choice',
    question: 'You pay off $300 of your credit card balance with cash. How does this affect the equation?',
    options: [
      'Assets -$300, Liabilities -$300',
      'Assets -$300, Equity -$300',
      'Liabilities +$300, Equity -$300',
      'Assets +$300, Liabilities +$300',
    ],
    correctAnswer: 0,
    explanation: 'Paying off debt reduces your Cash (asset) by $300 and reduces your Credit Card balance (liability) by $300. Equity is unchanged—you\'re just converting one obligation to another.',
    difficulty: 'medium',
  },
  {
    id: 'm2-q8',
    type: 'multiple-choice',
    question: 'What does "Owner\'s Equity" represent?',
    options: [
      'Total amount of debt owed',
      'Total value of all assets',
      'The ownership stake—what remains after liabilities are paid',
      'Monthly income',
    ],
    correctAnswer: 2,
    explanation: 'Owner\'s Equity represents the ownership stake in the business or your personal net worth—what would remain if you sold all assets and paid all debts.',
    difficulty: 'easy',
  },
  {
    id: 'm2-q9',
    type: 'multiple-choice',
    question: 'You buy a $25,000 car with $5,000 down payment and a $20,000 loan. What happens to the accounting equation?',
    options: [
      'Assets +$25,000, Liabilities +$25,000',
      'Assets +$20,000, Liabilities +$20,000',
      'Assets +$20,000 (Car +$25,000, Cash -$5,000), Liabilities +$20,000',
      'Assets -$5,000, Equity -$5,000',
    ],
    correctAnswer: 2,
    explanation: 'You gain a car asset worth $25,000, lose $5,000 cash, for a net asset increase of $20,000. You also take on a $20,000 loan (liability). The equation balances!',
    difficulty: 'hard',
  },
  {
    id: 'm2-q10',
    type: 'multiple-choice',
    question: 'Why must the accounting equation always balance?',
    options: [
      'It\'s just an arbitrary rule accountants follow',
      'Because every transaction affects at least two accounts by equal amounts',
      'It only needs to balance at year-end',
      'It doesn\'t actually have to balance',
    ],
    correctAnswer: 1,
    explanation: 'The equation must balance because every transaction affects at least two accounts by equal amounts. This is the foundation of double-entry bookkeeping and ensures accuracy.',
    difficulty: 'medium',
  },
];
