import type { QuizQuestion } from '../../types';

export const module06Quiz: QuizQuestion[] = [
  {
    id: 'm6-q1',
    type: 'multiple-choice',
    question: 'What does the Cash Flow Statement show?',
    options: [
      'Assets and liabilities at a point in time',
      'Revenue and expenses over a period',
      'Cash inflows and outflows over a period',
      'Changes in owner\'s equity',
    ],
    correctAnswer: 2,
    explanation: 'The Cash Flow Statement tracks actual cash movements (inflows and outflows) over a specific period, organized into operating, investing, and financing activities.',
    difficulty: 'easy',
  },
  {
    id: 'm6-q2',
    type: 'multiple-choice',
    question: 'Which section of the cash flow statement includes cash received from customers?',
    options: [
      'Operating Activities',
      'Investing Activities',
      'Financing Activities',
      'Supplemental Activities',
    ],
    correctAnswer: 0,
    explanation: 'Cash received from customers is part of Operating Activities—the day-to-day cash flows from core business operations.',
    difficulty: 'easy',
  },
  {
    id: 'm6-q3',
    type: 'multiple-choice',
    question: 'Where would you find "Purchase of Equipment" on the cash flow statement?',
    options: [
      'Operating Activities',
      'Investing Activities',
      'Financing Activities',
      'It wouldn\'t appear on the cash flow statement',
    ],
    correctAnswer: 1,
    explanation: 'Purchasing equipment is an Investing Activity because it involves acquiring long-term assets.',
    difficulty: 'easy',
  },
  {
    id: 'm6-q4',
    type: 'multiple-choice',
    question: 'Why is depreciation ADDED back to net income in the indirect method?',
    options: [
      'Because it represents cash received',
      'Because it\'s a non-cash expense that reduced net income',
      'Because equipment value increased',
      'Because it\'s required by law',
    ],
    correctAnswer: 1,
    explanation: 'Depreciation is a non-cash expense—it reduced net income but no cash actually left the business. We add it back to show true operating cash flow.',
    difficulty: 'medium',
  },
  {
    id: 'm6-q5',
    type: 'multiple-choice',
    question: 'If Accounts Receivable INCREASED during the period, what adjustment is made (indirect method)?',
    options: [
      'Add to net income',
      'Subtract from net income',
      'No adjustment needed',
      'Show in investing activities',
    ],
    correctAnswer: 1,
    explanation: 'An increase in A/R means revenue was recorded but cash wasn\'t collected yet. We subtract this from net income to show actual cash received was less.',
    difficulty: 'medium',
  },
  {
    id: 'm6-q6',
    type: 'multiple-choice',
    question: 'Where would "Dividends Paid" appear on the cash flow statement?',
    options: [
      'Operating Activities',
      'Investing Activities',
      'Financing Activities',
      'It doesn\'t appear on the cash flow statement',
    ],
    correctAnswer: 2,
    explanation: 'Dividends paid to shareholders are a Financing Activity—they represent cash returned to owners.',
    difficulty: 'easy',
  },
  {
    id: 'm6-q7',
    type: 'multiple-choice',
    question: 'What is the formula for Free Cash Flow?',
    options: [
      'Net Income − Depreciation',
      'Operating Cash Flow − Capital Expenditures',
      'Revenue − Expenses',
      'Total Assets − Total Liabilities',
    ],
    correctAnswer: 1,
    explanation: 'Free Cash Flow = Operating Cash Flow − Capital Expenditures. It represents cash available after maintaining/expanding the asset base.',
    difficulty: 'medium',
  },
  {
    id: 'm6-q8',
    type: 'multiple-choice',
    question: 'A company has positive operating cash flow, negative investing cash flow, and negative financing cash flow. What does this pattern suggest?',
    options: [
      'A struggling startup',
      'A mature, healthy company',
      'A company in financial distress',
      'A company about to go bankrupt',
    ],
    correctAnswer: 1,
    explanation: 'This pattern (+, −, −) indicates a mature, healthy company: generating cash from operations, investing in growth, and returning cash to stakeholders (debt repayment, dividends).',
    difficulty: 'hard',
  },
  {
    id: 'm6-q9',
    type: 'multiple-choice',
    question: 'Why might a profitable company run out of cash?',
    options: [
      'Revenue was recorded but customers haven\'t paid yet (high receivables)',
      'Profits were used to buy equipment',
      'Profits were used to pay off debt',
      'All of the above',
    ],
    correctAnswer: 3,
    explanation: 'All of these can cause a cash crunch despite profitability. Profit ≠ Cash. Accrual accounting, capital expenditures, and debt payments can all drain cash.',
    difficulty: 'medium',
  },
  {
    id: 'm6-q10',
    type: 'multiple-choice',
    question: 'The ending cash balance on the Cash Flow Statement should equal:',
    options: [
      'Net Income on the Income Statement',
      'Total Assets on the Balance Sheet',
      'Cash on the Balance Sheet',
      'Owner\'s Equity on the Balance Sheet',
    ],
    correctAnswer: 2,
    explanation: 'The ending cash balance on the Cash Flow Statement must match the Cash line on the Balance Sheet. This is how the two statements connect.',
    difficulty: 'easy',
  },
];
