import type { QuizQuestion } from '../../types';

export const module08Quiz: QuizQuestion[] = [
  {
    id: 'm8-q1',
    type: 'multiple-choice',
    question: 'What is the primary purpose of maintaining organized financial records?',
    options: [
      'To impress auditors',
      'To support decision-making, compliance, and audit readiness',
      'To create more paperwork',
      'To justify hiring an accountant',
    ],
    correctAnswer: 1,
    explanation: 'Organized financial records support informed decision-making, ensure compliance with tax laws and regulations, and prepare you for potential audits.',
    difficulty: 'easy',
  },
  {
    id: 'm8-q2',
    type: 'multiple-choice',
    question: 'How long should you generally keep tax returns and supporting documents?',
    options: [
      '1 year',
      '3 years',
      '7 years',
      'Forever',
    ],
    correctAnswer: 2,
    explanation: 'The IRS can audit returns up to 3 years back (6 years for significant underreporting). Keeping records for 7 years provides a safe buffer for most situations.',
    difficulty: 'medium',
  },
  {
    id: 'm8-q3',
    type: 'multiple-choice',
    question: 'What is bank reconciliation?',
    options: [
      'Opening a new bank account',
      'Comparing your records to the bank statement and resolving differences',
      'Depositing checks into your account',
      'Calculating interest earned',
    ],
    correctAnswer: 1,
    explanation: 'Bank reconciliation is the process of comparing your internal records against the bank statement to identify and resolve any discrepancies.',
    difficulty: 'easy',
  },
  {
    id: 'm8-q4',
    type: 'multiple-choice',
    question: 'Which of these is a common cause of differences between your records and bank statements?',
    options: [
      'Outstanding checks not yet cleared',
      'Using the same currency',
      'Having only one bank account',
      'Paying bills on time',
    ],
    correctAnswer: 0,
    explanation: 'Outstanding checks (checks you\'ve written but haven\'t been cashed yet) are a common reason your records may differ from the bank statement.',
    difficulty: 'easy',
  },
  {
    id: 'm8-q5',
    type: 'multiple-choice',
    question: 'What is a source document in accounting?',
    options: [
      'A financial statement',
      'An original record that provides evidence of a transaction',
      'A bank statement',
      'A budget forecast',
    ],
    correctAnswer: 1,
    explanation: 'Source documents (receipts, invoices, contracts) are the original evidence that a transaction occurred. They support journal entries and financial statements.',
    difficulty: 'easy',
  },
  {
    id: 'm8-q6',
    type: 'multiple-choice',
    question: 'What does "deposits in transit" mean in bank reconciliation?',
    options: [
      'Deposits that were returned',
      'Deposits recorded in your books but not yet on the bank statement',
      'International wire transfers',
      'Automatic deposits from your employer',
    ],
    correctAnswer: 1,
    explanation: 'Deposits in transit are deposits you\'ve recorded in your books that haven\'t yet appeared on the bank statement, usually because they were made near month-end.',
    difficulty: 'medium',
  },
  {
    id: 'm8-q7',
    type: 'multiple-choice',
    question: 'Which filing system approach organizes documents by type (invoices, receipts, contracts)?',
    options: [
      'Chronological filing',
      'Category-based filing',
      'Alphabetical filing',
      'Random filing',
    ],
    correctAnswer: 1,
    explanation: 'Category-based filing organizes documents by type, making it easy to find all invoices or all contracts in one place.',
    difficulty: 'easy',
  },
  {
    id: 'm8-q8',
    type: 'multiple-choice',
    question: 'What should you do if you find a bank error during reconciliation?',
    options: [
      'Ignore it—the bank is always right',
      'Adjust your books to match the bank',
      'Contact the bank immediately to report and resolve the error',
      'Wait until next month to see if it corrects itself',
    ],
    correctAnswer: 2,
    explanation: 'Banks can make errors too. If you find a bank error during reconciliation, contact them immediately with documentation to get it corrected.',
    difficulty: 'medium',
  },
  {
    id: 'm8-q9',
    type: 'multiple-choice',
    question: 'What is the 3-2-1 backup rule?',
    options: [
      '3 employees, 2 accounts, 1 password',
      '3 copies, 2 different media types, 1 off-site',
      '3 years of records, 2 filing cabinets, 1 computer',
      '3 banks, 2 credit cards, 1 savings account',
    ],
    correctAnswer: 1,
    explanation: 'The 3-2-1 backup rule recommends keeping 3 copies of your data on 2 different types of media with 1 copy stored off-site for disaster recovery.',
    difficulty: 'medium',
  },
  {
    id: 'm8-q10',
    type: 'multiple-choice',
    question: 'How often should you reconcile your bank accounts?',
    options: [
      'Once a year',
      'Quarterly',
      'Monthly',
      'Only when there\'s a problem',
    ],
    correctAnswer: 2,
    explanation: 'Monthly reconciliation is the standard practice. It catches errors quickly while transactions are still fresh and helps prevent fraud from going undetected.',
    difficulty: 'easy',
  },
  {
    id: 'm8-q11',
    type: 'multiple-choice',
    question: 'Which document would you need to verify a sales transaction?',
    options: [
      'Bank statement',
      'Invoice or receipt',
      'Tax return',
      'Budget report',
    ],
    correctAnswer: 1,
    explanation: 'An invoice or receipt is the source document that proves a sales transaction occurred, showing what was sold, for how much, and when.',
    difficulty: 'easy',
  },
  {
    id: 'm8-q12',
    type: 'multiple-choice',
    question: 'What is the adjusted book balance in a bank reconciliation?',
    options: [
      'The starting balance in your checkbook',
      'Your book balance after adding deposits in transit',
      'Your book balance after accounting for items like bank fees you hadn\'t recorded',
      'The ending balance on the bank statement',
    ],
    correctAnswer: 2,
    explanation: 'The adjusted book balance is your original book balance modified for items you hadn\'t yet recorded, like bank fees, interest earned, or NSF checks.',
    difficulty: 'medium',
  },
];
