import type { QuizQuestion } from '../../types';

export const module05Quiz: QuizQuestion[] = [
  {
    id: 'm5-q1',
    type: 'multiple-choice',
    question: 'What does the balance sheet show?',
    options: [
      'Revenue and expenses over a period',
      'Assets, liabilities, and equity at a specific point in time',
      'Cash inflows and outflows',
      'Changes in owner\'s equity',
    ],
    correctAnswer: 1,
    explanation: 'The balance sheet is a snapshot showing what a company owns (assets), owes (liabilities), and the residual claim of owners (equity) at a specific moment in time.',
    difficulty: 'easy',
  },
  {
    id: 'm5-q2',
    type: 'multiple-choice',
    question: 'Which of these is a current asset?',
    options: [
      'Building',
      'Patent',
      'Accounts Receivable',
      'Long-term Investments',
    ],
    correctAnswer: 2,
    explanation: 'Accounts Receivable is a current asset because it represents money owed by customers that will typically be collected within one year.',
    difficulty: 'easy',
  },
  {
    id: 'm5-q3',
    type: 'multiple-choice',
    question: 'Why are assets listed in order of liquidity?',
    options: [
      'It makes the balance sheet look better',
      'It shows how quickly assets can be converted to cash',
      'It\'s required by tax law',
      'It separates good assets from bad assets',
    ],
    correctAnswer: 1,
    explanation: 'Listing assets by liquidity (most liquid first) shows readers how quickly assets can be converted to cash, which is important for assessing short-term financial health.',
    difficulty: 'medium',
  },
  {
    id: 'm5-q4',
    type: 'multiple-choice',
    question: 'What is accumulated depreciation?',
    options: [
      'The total amount of depreciation expense since an asset was purchased',
      'The original cost of an asset',
      'The current market value of an asset',
      'Money set aside to buy new assets',
    ],
    correctAnswer: 0,
    explanation: 'Accumulated depreciation is the total depreciation recorded since an asset was acquired. It\'s subtracted from the asset\'s cost to show its "book value" on the balance sheet.',
    difficulty: 'medium',
  },
  {
    id: 'm5-q5',
    type: 'multiple-choice',
    question: 'A company has current assets of $100,000 and current liabilities of $50,000. What is the current ratio?',
    options: [
      '0.5',
      '1.0',
      '2.0',
      '$50,000',
    ],
    correctAnswer: 2,
    explanation: 'Current Ratio = Current Assets ÷ Current Liabilities = $100,000 ÷ $50,000 = 2.0. This means the company has $2 in current assets for every $1 in current liabilities.',
    difficulty: 'easy',
  },
  {
    id: 'm5-q6',
    type: 'multiple-choice',
    question: 'What does Retained Earnings represent?',
    options: [
      'Cash in the bank',
      'Money invested by shareholders',
      'Accumulated profits kept in the business over time',
      'The value of inventory',
    ],
    correctAnswer: 2,
    explanation: 'Retained Earnings represents the cumulative profits that have been kept in the business rather than paid out as dividends. It grows with net income and decreases with dividends.',
    difficulty: 'medium',
  },
  {
    id: 'm5-q7',
    type: 'multiple-choice',
    question: 'Which ratio measures financial leverage (how much debt vs. equity)?',
    options: [
      'Current Ratio',
      'Quick Ratio',
      'Debt-to-Equity Ratio',
      'Profit Margin',
    ],
    correctAnswer: 2,
    explanation: 'Debt-to-Equity Ratio (Total Liabilities ÷ Total Equity) measures how much debt a company uses relative to equity. Higher ratios indicate more financial leverage and risk.',
    difficulty: 'easy',
  },
  {
    id: 'm5-q8',
    type: 'multiple-choice',
    question: 'What is Working Capital?',
    options: [
      'Total Assets minus Total Liabilities',
      'Current Assets minus Current Liabilities',
      'Cash plus Accounts Receivable',
      'Revenue minus Expenses',
    ],
    correctAnswer: 1,
    explanation: 'Working Capital = Current Assets - Current Liabilities. It represents the cushion available for day-to-day operations and short-term obligations.',
    difficulty: 'medium',
  },
  {
    id: 'm5-q9',
    type: 'multiple-choice',
    question: 'How does net income from the Income Statement affect the Balance Sheet?',
    options: [
      'It increases Cash directly',
      'It increases Retained Earnings in Owner\'s Equity',
      'It decreases Liabilities',
      'It has no effect on the Balance Sheet',
    ],
    correctAnswer: 1,
    explanation: 'Net income flows to Retained Earnings on the Balance Sheet, increasing Owner\'s Equity. This is how the two financial statements connect.',
    difficulty: 'medium',
  },
  {
    id: 'm5-q10',
    type: 'multiple-choice',
    question: 'Which is NOT a component of Owner\'s Equity?',
    options: [
      'Common Stock',
      'Retained Earnings',
      'Accounts Payable',
      'Treasury Stock',
    ],
    correctAnswer: 2,
    explanation: 'Accounts Payable is a liability (money owed to suppliers), not equity. Owner\'s Equity includes Common Stock, Retained Earnings, and Treasury Stock (which reduces equity).',
    difficulty: 'easy',
  },
];
