import type { QuizQuestion } from '../../types';

export const module10Quiz: QuizQuestion[] = [
  {
    id: 'm10-q1',
    type: 'multiple-choice',
    question: 'Under cash basis accounting, when is revenue recognized?',
    options: [
      'When the service is performed',
      'When the invoice is sent',
      'When cash is received',
      'When the contract is signed',
    ],
    correctAnswer: 2,
    explanation: 'Under cash basis accounting, revenue is recorded when cash is actually received, regardless of when the service was performed or goods delivered.',
    difficulty: 'easy',
  },
  {
    id: 'm10-q2',
    type: 'multiple-choice',
    question: 'Under accrual basis accounting, when is revenue recognized?',
    options: [
      'When cash is received',
      'When the product is shipped or service is performed',
      'At the end of the accounting period',
      'When the customer pays',
    ],
    correctAnswer: 1,
    explanation: 'Under accrual accounting, revenue is recognized when earned (service performed or goods delivered), regardless of when cash is received.',
    difficulty: 'easy',
  },
  {
    id: 'm10-q3',
    type: 'multiple-choice',
    question: 'Which accounting method is required for publicly traded companies?',
    options: [
      'Cash basis',
      'Modified cash basis',
      'Accrual basis',
      'Either cash or accrual',
    ],
    correctAnswer: 2,
    explanation: 'GAAP requires publicly traded companies to use accrual basis accounting because it provides a more accurate picture of financial performance over time.',
    difficulty: 'medium',
  },
  {
    id: 'm10-q4',
    type: 'multiple-choice',
    question: 'What is an "accrued expense"?',
    options: [
      'An expense that has been paid but not yet incurred',
      'An expense that has been incurred but not yet paid',
      'An expense that will never be paid',
      'An expense that was paid twice',
    ],
    correctAnswer: 1,
    explanation: 'An accrued expense is one that has been incurred (you owe it) but hasn\'t been paid yet—like wages owed to employees at month-end.',
    difficulty: 'medium',
  },
  {
    id: 'm10-q5',
    type: 'multiple-choice',
    question: 'What is "deferred revenue"?',
    options: [
      'Revenue that will never be collected',
      'Revenue earned but not yet recorded',
      'Cash received for services not yet performed',
      'Revenue from a previous period',
    ],
    correctAnswer: 2,
    explanation: 'Deferred (unearned) revenue is cash received before the service is performed or goods delivered. It\'s a liability until earned.',
    difficulty: 'medium',
  },
  {
    id: 'm10-q6',
    type: 'multiple-choice',
    question: 'Which accounting method is simpler but may not show the true financial picture?',
    options: [
      'Accrual basis',
      'Cash basis',
      'Modified accrual',
      'GAAP method',
    ],
    correctAnswer: 1,
    explanation: 'Cash basis is simpler (just track when money moves) but can distort the true financial picture because it doesn\'t match revenues with related expenses.',
    difficulty: 'easy',
  },
  {
    id: 'm10-q7',
    type: 'multiple-choice',
    question: 'A company provides $10,000 of services in December but doesn\'t receive payment until January. Under accrual accounting, when is revenue recorded?',
    options: [
      'January (when cash received)',
      'December (when service provided)',
      'Split between December and January',
      'Neither until the contract ends',
    ],
    correctAnswer: 1,
    explanation: 'Under accrual accounting, revenue is recorded in December when the service was performed, even though cash isn\'t received until January.',
    difficulty: 'easy',
  },
  {
    id: 'm10-q8',
    type: 'multiple-choice',
    question: 'Which IRS threshold typically requires businesses to use accrual accounting?',
    options: [
      '$500,000 in gross receipts',
      '$1 million in gross receipts',
      '$25 million in gross receipts (3-year average)',
      'Any amount requires accrual',
    ],
    correctAnswer: 2,
    explanation: 'Generally, businesses with more than $25 million in average annual gross receipts (over 3 years) must use accrual accounting for tax purposes.',
    difficulty: 'hard',
  },
  {
    id: 'm10-q9',
    type: 'multiple-choice',
    question: 'What is the "matching principle" in accrual accounting?',
    options: [
      'Assets must match liabilities',
      'Expenses should be recorded in the same period as the revenues they help generate',
      'Debits must match credits',
      'Cash inflows must match cash outflows',
    ],
    correctAnswer: 1,
    explanation: 'The matching principle states that expenses should be recorded in the same period as the revenues they help generate, providing a clearer picture of profitability.',
    difficulty: 'medium',
  },
  {
    id: 'm10-q10',
    type: 'multiple-choice',
    question: 'Which accounting method typically results in more consistent financial statements over time?',
    options: [
      'Cash basis',
      'Accrual basis',
      'They produce identical results',
      'Depends on the industry',
    ],
    correctAnswer: 1,
    explanation: 'Accrual accounting produces more consistent statements because it matches revenues and expenses to the periods they belong to, smoothing out timing differences.',
    difficulty: 'medium',
  },
  {
    id: 'm10-q11',
    type: 'multiple-choice',
    question: 'You pay $12,000 upfront for a 12-month insurance policy starting January 1. Under accrual accounting, how much expense is recorded in January?',
    options: [
      '$12,000',
      '$1,000',
      '$0',
      '$6,000',
    ],
    correctAnswer: 1,
    explanation: 'Under accrual accounting, the $12,000 is initially recorded as prepaid insurance (asset). Each month, $1,000 is recognized as expense ($12,000 ÷ 12 months).',
    difficulty: 'medium',
  },
  {
    id: 'm10-q12',
    type: 'multiple-choice',
    question: 'What is "modified cash basis" accounting?',
    options: [
      'Cash basis with accrual adjustments for certain items',
      'Accrual basis with cash adjustments',
      'A method only used by governments',
      'The same as GAAP',
    ],
    correctAnswer: 0,
    explanation: 'Modified cash basis is a hybrid approach that uses cash accounting for most items but applies accrual treatment to specific items like inventory or long-term assets.',
    difficulty: 'medium',
  },
];
