import type { QuizQuestion } from '../../types';

export const module07Quiz: QuizQuestion[] = [
  {
    id: 'm7-q1',
    type: 'multiple-choice',
    question: 'What is the primary purpose of a budget?',
    options: [
      'To restrict all spending',
      'To track past expenses only',
      'To plan and allocate income intentionally',
      'To calculate net worth',
    ],
    correctAnswer: 2,
    explanation: 'A budget is a financial plan that allocates expected income to planned expenses and savings goals. It\'s about intentional spending, not restriction.',
    difficulty: 'easy',
  },
  {
    id: 'm7-q2',
    type: 'multiple-choice',
    question: 'In zero-based budgeting, what should Income minus all allocations equal?',
    options: [
      'Your savings goal',
      'Zero',
      'At least 20% of income',
      'Your emergency fund target',
    ],
    correctAnswer: 1,
    explanation: 'In zero-based budgeting, every dollar has a job. Income minus all allocations (expenses, savings, investments) should equal exactly zero.',
    difficulty: 'easy',
  },
  {
    id: 'm7-q3',
    type: 'multiple-choice',
    question: 'What does the 50/30/20 rule allocate 50% of income to?',
    options: [
      'Wants',
      'Savings',
      'Needs',
      'Investments',
    ],
    correctAnswer: 2,
    explanation: 'The 50/30/20 rule allocates 50% to needs (housing, utilities, food), 30% to wants (entertainment, dining out), and 20% to savings and debt repayment.',
    difficulty: 'easy',
  },
  {
    id: 'm7-q4',
    type: 'multiple-choice',
    question: 'Which budgeting method works best for people who tend to overspend in certain categories?',
    options: [
      'Traditional budgeting',
      '50/30/20 rule',
      'Envelope system',
      'Line-item budgeting',
    ],
    correctAnswer: 2,
    explanation: 'The envelope system creates visual and tangible spending limits. When the envelope is empty, you stop spending in that category—making it effective for overspenders.',
    difficulty: 'medium',
  },
  {
    id: 'm7-q5',
    type: 'multiple-choice',
    question: 'If you budgeted $500 for groceries but spent $600, what is the variance?',
    options: [
      '+$100 favorable',
      '-$100 unfavorable',
      '+$600 favorable',
      '-$500 unfavorable',
    ],
    correctAnswer: 1,
    explanation: 'Expense Variance = Budgeted - Actual = $500 - $600 = -$100. A negative variance for expenses means you overspent, which is unfavorable.',
    difficulty: 'medium',
  },
  {
    id: 'm7-q6',
    type: 'multiple-choice',
    question: 'Which of the following is a "favorable" variance?',
    options: [
      'Spending more than budgeted on entertainment',
      'Earning less than expected income',
      'Spending less than budgeted on transportation',
      'Missing your savings goal by $200',
    ],
    correctAnswer: 2,
    explanation: 'A favorable variance occurs when actual results are better than planned. Spending less than budgeted on expenses is favorable because you saved money.',
    difficulty: 'easy',
  },
  {
    id: 'm7-q7',
    type: 'multiple-choice',
    question: 'What is the first step in creating an effective budget?',
    options: [
      'Set financial goals',
      'Calculate your income',
      'Allocate money to savings',
      'Track current spending',
    ],
    correctAnswer: 1,
    explanation: 'Before you can budget, you need to know how much money you have coming in. Calculating your income (after taxes) is the essential first step.',
    difficulty: 'easy',
  },
  {
    id: 'm7-q8',
    type: 'multiple-choice',
    question: 'According to the 50/30/20 rule, which category should receive 20% of income?',
    options: [
      'Housing and utilities',
      'Entertainment and dining',
      'Savings and debt repayment',
      'Food and groceries',
    ],
    correctAnswer: 2,
    explanation: 'The 50/30/20 rule allocates 20% to savings (emergency fund, retirement) and debt repayment beyond minimums.',
    difficulty: 'easy',
  },
  {
    id: 'm7-q9',
    type: 'multiple-choice',
    question: 'Why is it important to review and adjust your budget regularly?',
    options: [
      'To make it more complicated',
      'Because income and expenses change over time',
      'To impress your accountant',
      'It\'s not important—set it and forget it',
    ],
    correctAnswer: 1,
    explanation: 'A budget is a living document. Life circumstances change—income varies, expenses fluctuate, and goals evolve. Regular review ensures your budget remains relevant and effective.',
    difficulty: 'easy',
  },
  {
    id: 'm7-q10',
    type: 'multiple-choice',
    question: 'What does variance percentage help you understand?',
    options: [
      'The total amount of money spent',
      'How significant a variance is relative to the budget',
      'The exact dollar amount of income',
      'The total number of transactions',
    ],
    correctAnswer: 1,
    explanation: 'Variance percentage (Variance / Budgeted Amount × 100) helps compare variances across different-sized categories. A $50 variance matters more in a $100 category (50%) than in a $2,000 category (2.5%).',
    difficulty: 'medium',
  },
  {
    id: 'm7-q11',
    type: 'multiple-choice',
    question: 'Which budgeting methodology requires the most time and effort?',
    options: [
      '50/30/20 rule',
      'Traditional budgeting',
      'Zero-based budgeting',
      'Envelope system',
    ],
    correctAnswer: 2,
    explanation: 'Zero-based budgeting requires assigning a purpose to every dollar and justifying every expense from scratch. While effective, it demands more time and attention than simpler methods.',
    difficulty: 'medium',
  },
  {
    id: 'm7-q12',
    type: 'multiple-choice',
    question: 'In the emergency fund scenario, what strategy helped Jordan reach the goal faster?',
    options: [
      'Earning more income',
      'Ignoring the credit card debt',
      'Using zero-based budgeting to cut discretionary spending',
      'Borrowing from family',
    ],
    correctAnswer: 2,
    explanation: 'Jordan used zero-based budgeting to identify and reduce discretionary spending, freeing up $950/month for debt payoff and savings—reducing the timeline from 43 months to about 13 months.',
    difficulty: 'medium',
  },
];
