import type { QuizQuestion } from '../../types';

export const module03Quiz: QuizQuestion[] = [
  {
    id: 'm3-q1',
    type: 'multiple-choice',
    question: 'What is the core principle of double-entry bookkeeping?',
    options: [
      'Every transaction should be recorded twice',
      'Every transaction affects at least two accounts with equal debits and credits',
      'Debits must always be larger than credits',
      'Only cash transactions need to be recorded',
    ],
    correctAnswer: 1,
    explanation: 'Double-entry bookkeeping requires that every transaction affects at least two accounts, and the total debits must equal total credits. This ensures the accounting equation stays balanced.',
    difficulty: 'easy',
  },
  {
    id: 'm3-q2',
    type: 'multiple-choice',
    question: 'According to the DEALER mnemonic, which accounts increase with a DEBIT?',
    options: [
      'Liabilities, Equity, Revenue',
      'Dividends, Expenses, Assets',
      'Debits, Entries, Accounts',
      'Cash, Revenue, Payables',
    ],
    correctAnswer: 1,
    explanation: 'DEALER: Dividends, Expenses, and Assets increase with a Debit. Liabilities, Equity, and Revenue increase with a Credit.',
    difficulty: 'medium',
  },
  {
    id: 'm3-q3',
    type: 'multiple-choice',
    question: 'What is the normal balance of a liability account?',
    options: [
      'Debit',
      'Credit',
      'Zero',
      'It depends on the transaction',
    ],
    correctAnswer: 1,
    explanation: 'Liabilities have a credit normal balance. They increase with credits and decrease with debits.',
    difficulty: 'easy',
  },
  {
    id: 'm3-q4',
    type: 'multiple-choice',
    question: 'You receive a $2,000 payment from a customer. Which is the correct journal entry?',
    options: [
      'Debit Service Revenue $2,000, Credit Cash $2,000',
      'Debit Cash $2,000, Credit Accounts Payable $2,000',
      'Debit Cash $2,000, Credit Service Revenue $2,000',
      'Debit Accounts Receivable $2,000, Credit Cash $2,000',
    ],
    correctAnswer: 2,
    explanation: 'When you receive cash, you debit Cash (asset increases). The credit goes to Service Revenue if it\'s new income, or Accounts Receivable if the customer was paying an existing invoice.',
    difficulty: 'medium',
  },
  {
    id: 'm3-q5',
    type: 'multiple-choice',
    question: 'In a journal entry, how should credits be formatted?',
    options: [
      'Listed first, flush left',
      'Listed first, indented',
      'Listed second, indented',
      'Listed second, flush left',
    ],
    correctAnswer: 2,
    explanation: 'In standard journal entry format, debits are listed first flush left, and credits are listed second and indented.',
    difficulty: 'easy',
  },
  {
    id: 'm3-q6',
    type: 'multiple-choice',
    question: 'You pay $500 for office rent. Which accounts are affected and how?',
    options: [
      'Debit Cash, Credit Rent Expense',
      'Debit Rent Expense, Credit Cash',
      'Debit Rent Expense, Credit Accounts Payable',
      'Debit Cash, Credit Rent Payable',
    ],
    correctAnswer: 1,
    explanation: 'Paying rent increases Rent Expense (debit) and decreases Cash (credit). Expenses increase with debits, and assets decrease with credits.',
    difficulty: 'medium',
  },
  {
    id: 'm3-q7',
    type: 'multiple-choice',
    question: 'What is a T-account used for?',
    options: [
      'Calculating taxes',
      'Visualizing how transactions affect individual accounts',
      'Recording transactions chronologically',
      'Preparing financial statements',
    ],
    correctAnswer: 1,
    explanation: 'T-accounts are visual tools that show debits on the left and credits on the right for a single account, making it easy to see how transactions affect that account\'s balance.',
    difficulty: 'easy',
  },
  {
    id: 'm3-q8',
    type: 'multiple-choice',
    question: 'In a chart of accounts, what does the number range 4000-4999 typically represent?',
    options: [
      'Assets',
      'Liabilities',
      'Expenses',
      'Revenue',
    ],
    correctAnswer: 3,
    explanation: 'The standard numbering convention is: 1xxx = Assets, 2xxx = Liabilities, 3xxx = Equity, 4xxx = Revenue, 5xxx = Expenses.',
    difficulty: 'medium',
  },
  {
    id: 'm3-q9',
    type: 'multiple-choice',
    question: 'You purchase $800 of supplies on credit (to pay later). What is the correct entry?',
    options: [
      'Debit Cash $800, Credit Supplies $800',
      'Debit Supplies $800, Credit Cash $800',
      'Debit Supplies $800, Credit Accounts Payable $800',
      'Debit Accounts Payable $800, Credit Supplies $800',
    ],
    correctAnswer: 2,
    explanation: 'When purchasing on credit, you gain an asset or expense (Supplies - debit) and create a liability (Accounts Payable - credit). Cash is not involved since you haven\'t paid yet.',
    difficulty: 'medium',
  },
  {
    id: 'm3-q10',
    type: 'multiple-choice',
    question: 'If your debits don\'t equal your credits, what does this indicate?',
    options: [
      'The business made a profit',
      'The business had a loss',
      'There is an error in the entries',
      'The accounting period has ended',
    ],
    correctAnswer: 2,
    explanation: 'Debits must always equal credits. If they don\'t balance, it indicates an error somewhere in the recording process. This self-checking feature is one of the main benefits of double-entry bookkeeping.',
    difficulty: 'easy',
  },
  {
    id: 'm3-q11',
    type: 'multiple-choice',
    question: 'A customer pays $1,500 they owed you from a previous invoice. What entry do you make?',
    options: [
      'Debit Cash $1,500, Credit Service Revenue $1,500',
      'Debit Cash $1,500, Credit Accounts Receivable $1,500',
      'Debit Accounts Receivable $1,500, Credit Cash $1,500',
      'Debit Service Revenue $1,500, Credit Cash $1,500',
    ],
    correctAnswer: 1,
    explanation: 'When collecting on an existing receivable, you debit Cash (asset increases) and credit Accounts Receivable (asset decreases). The revenue was already recorded when you invoiced them.',
    difficulty: 'hard',
  },
  {
    id: 'm3-q12',
    type: 'multiple-choice',
    question: 'What is the general ledger?',
    options: [
      'A list of all customers',
      'The chronological record of journal entries',
      'The master record of all accounts where journal entries are posted',
      'A summary of the year\'s financial activity',
    ],
    correctAnswer: 2,
    explanation: 'The general ledger is the master record of all accounts. Journal entries (chronological records) are "posted" to the general ledger, which shows the running balance for each account.',
    difficulty: 'easy',
  },
];
