import type { QuizQuestion } from '../../types';

export const module04Quiz: QuizQuestion[] = [
  {
    id: 'm4-q1',
    type: 'multiple-choice',
    question: 'What does the income statement measure?',
    options: [
      'Assets and liabilities at a point in time',
      'Revenue, expenses, and profit/loss over a period of time',
      'Cash inflows and outflows',
      'The value of a company\'s stock',
    ],
    correctAnswer: 1,
    explanation: 'The income statement (also called P&L) measures financial performance over a period of time by showing revenues minus expenses equals net income or loss.',
    difficulty: 'easy',
  },
  {
    id: 'm4-q2',
    type: 'multiple-choice',
    question: 'When should revenue be recognized under accrual accounting?',
    options: [
      'When cash is received',
      'When the invoice is sent',
      'When the revenue is earned',
      'At the end of the fiscal year',
    ],
    correctAnswer: 2,
    explanation: 'Under accrual accounting, revenue is recognized when earned—when goods are delivered or services are performed—regardless of when cash is received.',
    difficulty: 'medium',
  },
  {
    id: 'm4-q3',
    type: 'multiple-choice',
    question: 'What is Gross Profit?',
    options: [
      'Total revenue before any deductions',
      'Revenue minus Cost of Goods Sold',
      'Revenue minus all expenses',
      'Net Income before taxes',
    ],
    correctAnswer: 1,
    explanation: 'Gross Profit = Revenue - Cost of Goods Sold. It shows profitability from core products/services before operating expenses.',
    difficulty: 'easy',
  },
  {
    id: 'm4-q4',
    type: 'multiple-choice',
    question: 'What does the "matching principle" require?',
    options: [
      'Debits must equal credits',
      'Assets must equal liabilities plus equity',
      'Expenses should be recorded in the same period as the revenue they help generate',
      'All transactions must have supporting documentation',
    ],
    correctAnswer: 2,
    explanation: 'The matching principle requires expenses to be recorded in the same accounting period as the revenue they helped generate, ensuring accurate profit measurement.',
    difficulty: 'medium',
  },
  {
    id: 'm4-q5',
    type: 'multiple-choice',
    question: 'A company has Revenue of $100,000, COGS of $40,000, and Operating Expenses of $30,000. What is the Operating Income?',
    options: [
      '$100,000',
      '$60,000',
      '$30,000',
      '$70,000',
    ],
    correctAnswer: 2,
    explanation: 'Operating Income = Revenue - COGS - Operating Expenses = $100,000 - $40,000 - $30,000 = $30,000. (Gross Profit of $60,000 minus $30,000 operating expenses)',
    difficulty: 'medium',
  },
  {
    id: 'm4-q6',
    type: 'multiple-choice',
    question: 'Which of the following is a non-operating expense?',
    options: [
      'Salaries',
      'Rent',
      'Interest expense',
      'Advertising',
    ],
    correctAnswer: 2,
    explanation: 'Interest expense is a non-operating expense because it relates to financing activities, not core business operations. Salaries, rent, and advertising are operating expenses.',
    difficulty: 'easy',
  },
  {
    id: 'm4-q7',
    type: 'multiple-choice',
    question: 'If a company has $500,000 in revenue and $75,000 in net income, what is the net profit margin?',
    options: [
      '6.7%',
      '15%',
      '25%',
      '85%',
    ],
    correctAnswer: 1,
    explanation: 'Net Profit Margin = Net Income ÷ Revenue × 100 = $75,000 ÷ $500,000 × 100 = 15%',
    difficulty: 'medium',
  },
  {
    id: 'm4-q8',
    type: 'multiple-choice',
    question: 'What does "EBIT" stand for?',
    options: [
      'Earnings Before Income Taxes',
      'Earnings Before Interest and Taxes',
      'Expenses Before Interest and Taxes',
      'Equity Before Interest and Taxes',
    ],
    correctAnswer: 1,
    explanation: 'EBIT stands for Earnings Before Interest and Taxes, also known as Operating Income. It measures profitability from core operations.',
    difficulty: 'easy',
  },
  {
    id: 'm4-q9',
    type: 'multiple-choice',
    question: 'You pay $6,000 in January for 12 months of insurance. How much expense do you record in January?',
    options: [
      '$6,000',
      '$500',
      '$0 until the policy expires',
      '$3,000',
    ],
    correctAnswer: 1,
    explanation: 'Following the matching principle, you spread the expense over the coverage period: $6,000 ÷ 12 months = $500 per month. In January, you record $500 as insurance expense.',
    difficulty: 'hard',
  },
  {
    id: 'm4-q10',
    type: 'multiple-choice',
    question: 'What happens to Net Income at the end of an accounting period?',
    options: [
      'It disappears',
      'It becomes Cash on the Balance Sheet',
      'It flows to Retained Earnings on the Balance Sheet',
      'It is distributed to shareholders automatically',
    ],
    correctAnswer: 2,
    explanation: 'Net Income flows to Retained Earnings on the Balance Sheet, increasing Owner\'s Equity. This connects the Income Statement to the Balance Sheet.',
    difficulty: 'medium',
  },
];
