import type { QuizQuestion } from '../../types';

export const module11Quiz: QuizQuestion[] = [
  {
    id: 'm11-q1',
    type: 'multiple-choice',
    question: 'What is the purpose of financial ratio analysis?',
    options: [
      'To replace financial statements',
      'To evaluate financial performance and compare with benchmarks',
      'To calculate taxes owed',
      'To prepare budgets',
    ],
    correctAnswer: 1,
    explanation: 'Financial ratio analysis helps evaluate a company\'s performance, efficiency, and financial health by comparing metrics over time and against industry benchmarks.',
    difficulty: 'easy',
  },
  {
    id: 'm11-q2',
    type: 'multiple-choice',
    question: 'What does the current ratio measure?',
    options: [
      'Profitability',
      'Short-term liquidity (ability to pay current obligations)',
      'Long-term solvency',
      'Revenue growth',
    ],
    correctAnswer: 1,
    explanation: 'The current ratio (Current Assets / Current Liabilities) measures the ability to pay short-term obligations. A ratio above 1 means you have more current assets than current liabilities.',
    difficulty: 'easy',
  },
  {
    id: 'm11-q3',
    type: 'multiple-choice',
    question: 'A company has current assets of $500,000 and current liabilities of $250,000. What is its current ratio?',
    options: [
      '0.5',
      '1.0',
      '2.0',
      '250,000',
    ],
    correctAnswer: 2,
    explanation: 'Current Ratio = Current Assets / Current Liabilities = $500,000 / $250,000 = 2.0. This means the company has $2 of current assets for every $1 of current liabilities.',
    difficulty: 'easy',
  },
  {
    id: 'm11-q4',
    type: 'multiple-choice',
    question: 'What is the difference between the current ratio and quick ratio?',
    options: [
      'Quick ratio includes inventory; current ratio excludes it',
      'Current ratio includes inventory; quick ratio excludes it',
      'They are the same',
      'Quick ratio uses total assets; current ratio uses current assets',
    ],
    correctAnswer: 1,
    explanation: 'The quick ratio excludes inventory from current assets because inventory may be difficult to convert to cash quickly. It provides a more conservative measure of liquidity.',
    difficulty: 'medium',
  },
  {
    id: 'm11-q5',
    type: 'multiple-choice',
    question: 'What does the debt-to-equity ratio measure?',
    options: [
      'Profitability',
      'Liquidity',
      'Financial leverage (how much the company relies on debt)',
      'Efficiency',
    ],
    correctAnswer: 2,
    explanation: 'Debt-to-equity ratio (Total Debt / Total Equity) shows how much a company is financed by debt versus equity. Higher ratios indicate more leverage and potentially more risk.',
    difficulty: 'medium',
  },
  {
    id: 'm11-q6',
    type: 'multiple-choice',
    question: 'A company has net income of $100,000 and revenue of $500,000. What is its net profit margin?',
    options: [
      '5%',
      '20%',
      '50%',
      '500%',
    ],
    correctAnswer: 1,
    explanation: 'Net Profit Margin = Net Income / Revenue × 100 = $100,000 / $500,000 × 100 = 20%. This means 20 cents of every revenue dollar becomes profit.',
    difficulty: 'easy',
  },
  {
    id: 'm11-q7',
    type: 'multiple-choice',
    question: 'What does ROE (Return on Equity) measure?',
    options: [
      'How efficiently the company uses assets',
      'How much profit is generated from shareholders\' investment',
      'How quickly inventory is sold',
      'How much debt the company has',
    ],
    correctAnswer: 1,
    explanation: 'Return on Equity (Net Income / Shareholders\' Equity) measures how effectively a company generates profit from the money shareholders have invested.',
    difficulty: 'medium',
  },
  {
    id: 'm11-q8',
    type: 'multiple-choice',
    question: 'What is horizontal analysis?',
    options: [
      'Comparing financial data across different companies',
      'Comparing financial data over time periods',
      'Expressing all items as percentages of a base amount',
      'Analyzing only the balance sheet',
    ],
    correctAnswer: 1,
    explanation: 'Horizontal analysis (trend analysis) compares financial data over time periods to identify trends. It shows how each line item has changed year over year.',
    difficulty: 'medium',
  },
  {
    id: 'm11-q9',
    type: 'multiple-choice',
    question: 'What is vertical analysis?',
    options: [
      'Comparing data across time periods',
      'Expressing each item as a percentage of a base amount (like total revenue)',
      'Only analyzing equity accounts',
      'Comparing to competitors',
    ],
    correctAnswer: 1,
    explanation: 'Vertical analysis expresses each line item as a percentage of a base figure (revenue for income statement, total assets for balance sheet). It reveals the relative size of each component.',
    difficulty: 'medium',
  },
  {
    id: 'm11-q10',
    type: 'multiple-choice',
    question: 'What does the inventory turnover ratio measure?',
    options: [
      'How much inventory is on hand',
      'How quickly inventory is sold and replaced',
      'The value of inventory at year-end',
      'Inventory shrinkage',
    ],
    correctAnswer: 1,
    explanation: 'Inventory turnover (Cost of Goods Sold / Average Inventory) measures how many times inventory is sold and replaced during a period. Higher turnover usually indicates efficient operations.',
    difficulty: 'medium',
  },
  {
    id: 'm11-q11',
    type: 'multiple-choice',
    question: 'Why is it important to compare ratios to industry benchmarks?',
    options: [
      'Industry benchmarks are required by law',
      'Ratios have little meaning without context and comparison',
      'All industries have the same ideal ratios',
      'Benchmarks eliminate the need for financial statements',
    ],
    correctAnswer: 1,
    explanation: 'A ratio alone has limited meaning. Comparing to industry benchmarks provides context—a 2% profit margin might be excellent for grocery stores but poor for software companies.',
    difficulty: 'easy',
  },
  {
    id: 'm11-q12',
    type: 'multiple-choice',
    question: 'What limitation should you keep in mind when using ratio analysis?',
    options: [
      'Ratios are always accurate predictors of future performance',
      'Ratios only work for large companies',
      'Ratios are based on historical data and accounting policies can vary',
      'Ratios replace the need to read financial statements',
    ],
    correctAnswer: 2,
    explanation: 'Ratios are based on historical financial data and can be affected by different accounting methods. They\'re useful tools but shouldn\'t be the only basis for decisions.',
    difficulty: 'medium',
  },
];
